modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="avram"
version="1.0.0"
displayName="avram"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="noam1, MCreator"

[[dependencies.avram]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"



